var five = 5;
var ten = 10;
console.log("Test 1: Five is equal to 5?");
console.log(five == 5);
console.log("Test 2: Ten is equal to 10?");
console.log(ten == 10);
console.log("Test 3: Ten is equal to 5?");
console.log(ten == 5);
console.log("Test 4: Five is equal to 10?");
console.log(five == 10);
console.log("Test 5: Five is not equal to 5?");
console.log(five != 5);
console.log("Test 6: Ten is not equal to 10?");
console.log(ten != 10);
console.log("Test 7: Ten is not equal to 5?");
console.log(ten != 5);
console.log("Test 8: Five is not equal to 10?");
console.log(five != 10);
console.log("Test 9: Ten is greater than  5?");
console.log(ten > 5);
console.log("Test 10: Five is greater than 10?");
console.log(five > 10);
console.log("Test 11: Ten is lesser than  5?");
console.log(ten < 5);
console.log("Test 12: Five is lesser than 10?");
console.log(five < 10);
